---
title: "Minimum wage impacts on employment using IRP5 files"
date: "r format(Sys.time(), "%Y%m%d %R")"
output: 
  litedown::html_format:
    meta:
      css: ["MyCSS.css", "@default", "@tabsets", "@copy-button"]
      js: ["@sidenotes", "@appendix", "@tabsets", "@copy-button"]
#### output: html_document
#### path <- "W:/epguest/seiro_ito/"; litedown::fuse(paste0(pathprogram, "IRP5Impacts.rmd"))
---
```{css, echo=F}
.SeiroBenign {
  background-color: #FFEBCD;
  padding: 0.5em; /*文字まわり（上下左右）の余白*/
  /* border: 1px solid yellow; */
  /* font-weight: bold; */
}
.SeiroLightGreen {
  background-color: #D0F0C0; /* Tea green */
  padding: 0.5em; /*文字まわり（上下左右）の余白*/
  font-family: Lucida Sans;
  /* border: 1px solid yellow; */
  /* font-weight: bold; */
}
#### Default height of a block
pre {
  max-height: 700px;
  overflow-y: auto;
}
```


# Setup

```{r read setup from child file, child='setup.Rmd', message = F, warning = F}
#### setup.rmd sets eval, echo, time to T
```
```{r read functions from child file, child='destatfactor.Rmd', message = F, warning = F}
```

```{r setup, eval = F, echo = F}
library(qs); library(data.table); library(ggplot2)
library(rmarkdown); library(fixest)
library(knitr); library(tufte)
library(litedown)
litedown::reactor(
  echo = TRUE,
  eval = TRUE, 
  time = TRUE
)
options(htmltools.dir.version = FALSE, width = 100)
#### invalidate cache when the tufte version changes
knitr::opts_chunk$set(
  tidy = FALSE, cache.extra = packageVersion('tufte'), 
  margin_references = TRUE,
  #### remove leading hashes in html output
  comment = "", 
  echo = T, cache = F, eval = F,
  class.source = "SeiroBenign", class.output = "SeiroLightGreen"
  )
grepout <- function(str, x)
  # returns element of match (not numbers)
  x[grep(str, x, perl = T)]
table0 <- function(x) table(x, useNA = "ifany")
GeoLevel <- c("Prv", "Dis", "Loc", "Mai")
geovars <- c("busprov_geo", "busdistmuni_geo", 
  "buslocmuni_geo", "busmainplc_geo")
```





# Estimation

We use the TWFE event sudy specification. 


## Straight estimation

```{r select estimation sample}
Lf <- qread(paste0(pathsaveddata, "EstSample_Ag.qs"), nthreads = 13)
#### Complete panel
#### definition of complete: observed everyear in start year - 2020
Lf[, c("Num", "DiffTY", "MaxDiffTY") := 
  .(1:.N, c(0L, diff(taxyear)), max(taxyear)-min(taxyear)+1), 
  by = EstID]
Lf[, GapInTY := 0L]
Lf[EstID %in% EstID[DiffTY > 1 & taxyear <= 2020], GapInTY := 1L]
print(Lf[Num == 1L, .(num = .N), by = .(GapInTY, taxyear)][
  order(GapInTY, taxyear), ])
Lf[, num := 1:.N, by = .(EstID, taxyear)]
print(Lf[num == 1L, ][, 
  .(
         Micro = sum(JobsMP0>0 & JobsMP0<10, na.rm = T)
    , NotMicro = sum(JobsMP0>=10, na.rm = T)
  ), by = taxyear])
#### HHI grouping
Lf[, HHI0 := HHI[!is.na(HHI)][1], by = EstID]
Lf[HHI0 <= median(HHI0[taxyear == 2012], na.rm = T), HHILevel := "Below"]
Lf[HHI0 > median(HHI0[taxyear == 2012], na.rm = T), HHILevel := "Above"]
Lf[, HHILevel := factor(HHILevel)]
DESS <- vector(length = 2, mode = "list")
names(DESS) <- c("02", "10")
DESS <- list("2010" = DESS, "2012" = DESS)
Jbs <- c(2, 10)
Yrs <- c(2010, 2012)
####for (jj in 1:lengh(Jbs)) {
for (jj in 1) {
  if (Jbs[jj] < 10) 
    Jb <- paste0(0, Jbs[jj]) else 
    Jb <- Jbs[jj]
  LfC <- Lf[
      grepl("^B", FirstYear2013) &  #### first year < 2013
              JobsMP0 >= Jbs[jj] &  #### baseline jobs > Jbs[jj]
               DurMonthMarch > 0 &  #### job duration > 0 month
                   GapInTY == 0L ,  #### no gap in taxyear for all observed periods
      c(geovars, "EstID", 
        grepout("tax|Exist|Job|Dur|Cr|An|Fo|Are|Work|Sha|HHI|nc|Emp|FA|Siz|Sub", 
        colnames(Lf))), with = F
    ]
  LfCE <- LfC[ExistedBefore2013 == 1L, ]
  LfCEb <- LfCE[grepl("Be", HHILevel), ]
  LfCEa <- LfCE[grepl("Ab", HHILevel), ]
  print(rbind(
      Lf    = table(Lf[, taxyear])
    , LfC   = table(LfC[, taxyear])
    , LfCE  = table(LfCE[, taxyear])
    , LfCEb = table(LfCEb[, taxyear])
    , LfCEa = table(LfCEa[, taxyear])
  ))
####  for (yy in 1:length(Yrs)) {
  for (yy in 1) {
    Yr <- Yrs[yy]
    LfYr    <- Lf[taxyear >= Yr, ]
    LfCYr   <- LfC[taxyear >= Yr, ]
    LfCEYr  <- LfCE[taxyear >= Yr, ]
    LfCEbYr <- LfCEb[taxyear >= Yr, ]
    LfCEaYr <- LfCEa[taxyear >= Yr, ]
    assign(paste0("Lf",    Yr, Jb), LfYr)
    assign(paste0("LfC",   Yr, Jb), LfCYr)
    assign(paste0("LfCE",  Yr, Jb), LfCEYr)
    assign(paste0("LfCEb", Yr, Jb), LfCEbYr)
    assign(paste0("LfCEa", Yr, Jb), LfCEaYr)
    qsave(LfYr,    paste0(pathdata, "Lf",    Yr, Jb, ".qs"))
    qsave(LfCYr,   paste0(pathdata, "LfC",   Yr, Jb, ".qs"))
    qsave(LfCEYr,  paste0(pathdata, "LfCE",  Yr, Jb, ".qs"))
    qsave(LfCEbYr, paste0(pathdata, "LfCEb", Yr, Jb, ".qs"))
    qsave(LfCEaYr, paste0(pathdata, "LfCEa", Yr, Jb, ".qs"))
    #### destat for each data
    #### To be specified using destat and destatfactor
    iifac <- sapply(LfCYr, is.factor)
    iich  <- sapply(LfCYr, is.character)
    des1  <- destat(LfCYr[, which(!(iifac|iich)), with = F])
    des2  <- destatfactor(LfCYr, IgnoreIfAbove = 8)
    dess  <- rbind(des1, des2)
    DESS[[yy]][[jj]] <- dess
    #### LaTeX table
    ltb1 <- latextab.simple(des1, 
      hcenter = c(8, rep(.8, 5), rep(.6, 2), .5, .3, .3), 
      unit = "cm")
    ltb2 <- latextab.simple(des2, 
      hcenter = c(8, rep(.8, 5), rep(.6, 2), .5, .3, .3), 
      unit = "cm")
    ltb <- matrix(c(
        ltb1[1]
      , paste0("\\multicolumn{", des1, "}{l}{\\textit{\\footnotesize A. Continuous variables}}\\\\") 
      , ltb1[-length(ltb1)]
      , paste0("\\multicolumn{", des1, "}{l}{\\textit{\\footnotesize B. Categorical variables}}\\\\") 
      , ltb2[-1]
    ))
    write.tablev(ltb1, paste0(pathresults, "Destat", Yr, Jb, "_1.tex"))
    write.tablev(ltb2, paste0(pathresults, "Destat", Yr, Jb, "_2.tex"))
    write.tablev(ltb , paste0(pathresults, "Destat", Yr, Jb,   ".tex"))
    #### HTML table
    library(kableExtra)
    ktb <- data.table(dess)
    kt <- kable(ktb, align = 
     paste0("r", paste0(rep("c", ncol(ktb)-1), collapse = "")), 
     caption = paste0("Descriptive statistics ", Yr, "-2022, Job0 cutoff", Jb))
    kt <- column_spec(kt, 1, width = "9cm; min-width:9cm;")
    kt <- column_spec(kt, 2:6, width = "2.0cm; min-width:2.0cm;")
    kt <- kableExtra::footnote(kt, general = "Sample of agricultural establishments.")
    qsave(kt, paste0(pathresults, "Destat", Yr, Jb, ".qs"))
    assign(paste0("Destat", Yr, Jb), kt)
  }
}
qsave(DESS, paste0(pathresults, "DESS.qs"))
LfCEb[order(EstID, taxyear), 
  .(EstID, taxyear, JobsMP, rJobsMP, dJobsMP, FAMP )][1:30, ]
LfCEa[order(EstID, taxyear), 
  .(EstID, taxyear, JobsMP, rJobsMP, dJobsMP, FAMP )][1:30, ]
Destat201002
```

```{r examining estimation data}
LfCYr <- LfC201002
LfCYr[EstID %in% EstID[dJobsMP < -1000], ][order(EstID, taxyear),
  .(busdistmuni_geo, buslocmuni_geo, busmainplc_geo, taxrefno, EstID, 
  taxyear, JobsMP, dJobsMP, Share, FAMP)][1:50, ]
LfCYr[, FAclass := "low"]
LfCYr[.2 < FAMP0 & FAMP0 <= .5, FAclass := "mid"]
LfCYr[FAMP0 > .5, FAclass := "high"]
LfCYr[, FAclass := factor(FAclass, levels = c("low", "mid", "high"))]
lfdata <- unique(LfCYr[, .(busdistmuni_geo, buslocmuni_geo, 
  busmainplc_geo, EstID, taxyear, 
  rJobsMP, dJobsMP, JobsMP, JobsMP0, 
  Share, FAMP, FAMP0, FAclass)])
rbind(Lf = dim(Lf), LfCYr = dim(LfCYr), lfdata = dim(lfdata))
destat(lfdata)
destatfactor(lfdata)
#### plot rJobsMP after dropping outliers
lfdata.dropped <- lfdata[
  EstID %in% intersect(EstID[abs(rJobsMP) < 200], EstID[dJobsMP > -1000]), ]
rbind(
  lfdata = dim(lfdata),
  dropped = dim(lfdata.dropped)
)
ggplot(data=lfdata.dropped, 
  aes(x = taxyear, y = rJobsMP, group = EstID, colour = FAclass)) +
geom_line() +
scale_y_continuous(transform = "log10") + 
guides(
  colour = guide_legend(title = "FA classes", nrow = 1)
  ) +
theme(
  legend.text=element_text(size=9),
  legend.position = "bottom"
)
```


```{r estimation with various Job0 and start year}
#### for (Jb in c(2, 10)) {
for (Jb in 2) {
  if (Jb < 10) Jb <- paste0(0, Jb)
####  for (Yr in c(2010, 2012)) {
  for (Yr in 2010) {
    LfYr    <- get(paste0("Lf",    Yr, Jb))
    LfCYr   <- get(paste0("LfC",   Yr, Jb))
    LfCEYr  <- get(paste0("LfCE",  Yr, Jb))
    LfCEbYr <- get(paste0("LfCEb", Yr, Jb))
    LfCEaYr <- get(paste0("LfCEa", Yr, Jb))
    library(fixest)
    esLfYr <- feols(JobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfYr)
    esLfCYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCYr)
    esLfCEYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCEYr)
    #### Subsample: High and low concentrated markets
    esLfCEaYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCEaYr)
    esLfCEbYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCEbYr)
    library(ggfixest)
    eslistYr <-  list(
        "All sample" = esLfYr, 
        "Complete panel" = esLfCYr, 
        "Existed firms, all sample" = esLfCEYr, 
        "Existed firms, high concentrated markets" = esLfCEaYr, 
        "Existed firms, low concentrated markets" = esLfCEbYr 
      )
    gFEYr <- ggiplot(eslistYr,
      ref.line = 2012, 
      main = "Job impacts: Low and high concentration",
      xlab = "Tax year (March - Februray)",
      multi_style = "facet",
      geom_style = "ribbon",
      theme = theme(
        axis.text.x = element_text(angle = 90, vjust = .5),
        legend.position = "none"
        )
    ) + 
    scale_x_continuous(limits = c(Yr, 2022), breaks = Yr:2022) +
    scale_y_continuous(limits = c(15, -10)) 
    if (Jb == 2) Jb <- paste0("0", Jb)
    ggsave(
    paste0(pathresults, "Results", Yr, "-2022Job", Jb, ".jpg")
      , gFE, width = 8*2, height = 4*2, units = "cm",
      dpi = 300
     )
    gFEYr
    lapply(eslistYr, summary)
    assign(paste0("eslist", Yr, Jb), eslistYr)
    assign(paste0("gFE",    Yr, Jb), gFEYr)
    qsave(eslistYr, paste0(pathresults, "eslist", Yr, Jb, ".qs"))
  }
}
gFE201002
```

## Winsorizing


```{r select winsorized estimation sample, eval = F}
Lf <- qread(paste0(pathsaveddata, "EstSample_Ag.qs"), nthreads = 13)
Lf[, num := 1:.N, by = .(EstID, taxyear)]
Lfw <- Lf[num == 1L & (
    !(EstID %in% EstID[abs(rJobsMP) > 2 | abs(dJobsMP) > 3000]) # small changes
  ) , ]
rbind(Lf=dim(Lf), Lfw=dim(Lfw))
Lfw[, 
  .(
         Micro = sum(JobsMP0>0 & JobsMP0<10, na.rm = T)
    , NotMicro = sum(JobsMP0>=10, na.rm = T)
  ), by = taxyear]
DESSw <- vector(length = 2, mode = "list")
names(DESSw) <- c("02", "10")
DESSw <- list("2010" = DESSw, "2012" = DESSw)
Jbs <- c(2, 10)
Yrs <- c(2010, 2012)
for (jj in 1:lengh(Jbs)) {
  if (Jbs[jj] < 10) 
    Jb <- paste0(0, Jbs[jj]) else 
    Jb <- Jbs[jj]
  LfwC <- Lfw[
      grepl("^B", FirstYear2013) & 
              JobsMP0 >= Jbs[jj] & 
               DurMonthMarch > 0 & 
           ReportEveryYear == 1L , 
    ]
  LfwC[HHI <= median(HHI[taxyear == 2012], na.rm = T), HHILevel := "Below"]
  LfwC[HHI > median(HHI[taxyear == 2012], na.rm = T), HHILevel := "Above"]
  LfwC[, HHILevel := factor(HHILevel)]
  LfwCE <- LfwC[ExistedBefore2013 == 1L, ]
  LfwCEb <- LfwCE[grepl("Be", HHILevel), ]
  LfwCEa <- LfwCE[grepl("Ab", HHILevel), ]
  print(rbind(
      Lfw    = table(Lfw[, taxyear])
    , LfwC   = table(LfwC[, taxyear])
    , LfwCE  = table(LfwCE[, taxyear])
    , LfwCEb = table(LfwCEb[, taxyear])
    , LfwCEa = table(LfwCEa[, taxyear])
  ))
  for (yy in 1:length(Yrs)) {
    Yr <- Yrs[yy]
    LfYr    <- Lfw[taxyear >= Yr, ]
    LfCYr   <- LfwC[taxyear >= Yr, ]
    LfCEYr  <- LfwCE[taxyear >= Yr, ]
    LfCEbYr <- LfwCEb[taxyear >= Yr, ]
    LfCEaYr <- LfwCEa[taxyear >= Yr, ]
    assign(paste0("Lfw",    Yr, Jb), LfYr)
    assign(paste0("LfwC",   Yr, Jb), LfCYr)
    assign(paste0("LfwCE",  Yr, Jb), LfCEYr)
    assign(paste0("LfwCEb", Yr, Jb), LfCEbYr)
    assign(paste0("LfwCEa", Yr, Jb), LfCEaYr)
    #### destat for each data
    #### To be specified using destat and destatfactor
    iifac <- sapply(LfCYr, is.factor)
    iich  <- sapply(LfCYr, is.character)
    des1  <- destat(LfCYr[, which(!(iifac|iich)), with = F])
    des2  <- destatfactor(LfCYr)
    dess  <- rbind(des1, des2)
    DESSw[[yy]][[jb]] <- dess
    #### LaTeX table
    ltb1 <- latextab.simple(des1, 
      hcenter = c(8, rep(.8, 5), rep(.6, 2), .5, .3, .3), 
      unit = "cm")
    ltb2 <- latextab.simple(des2, 
      hcenter = c(8, rep(.8, 5), rep(.6, 2), .5, .3, .3), 
      unit = "cm")
    ltb <- matrix(c(
        ltb1[1]
      , paste0("\\multicolumn{", des1, "}{l}{\\textit{\\footnotesize A. Continuous variables}}\\\\") 
      , ltb1[-length(ltb1)]
      , paste0("\\multicolumn{", des1, "}{l}{\\textit{\\footnotesize B. Categorical variables}}\\\\") 
      , ltb2[-1]
    ))
    write.tablev(ltb1, paste0(pathresults, "Destat", Yr, Jb, "w_1.tex"))
    write.tablev(ltb2, paste0(pathresults, "Destat", Yr, Jb, "w_2.tex"))
    write.tablev(ltb , paste0(pathresults, "Destat", Yr, Jb,   "w.tex"))
    #### HTML table
    library(kableExtra)
    ktb <- data.table(dess)
    kt <- kable(ktb, align = 
     paste0("r", paste0(rep("c", ncol(ktb)-1), collapse = "")), 
     caption = paste0("Descriptive statistics ", Yr, "-2022, Job0 cutoff", Jb))
    kt <- column_spec(kt, 1, width = "9cm; min-width:9cm;")
    kt <- column_spec(kt, 2:6, width = "2.0cm; min-width:2.0cm;")
    kt <- kableExtra::footnote(kt, general = "Sample of agricultural establishments.")
    qsave(kt, paste0(pathresults, "Destatw", Yr, Jb, ".qs"))
    assign(paste0("Destatw", Yr, Jb), kt)
  }
}
qsave(DESSw, paste0(pathresults, "DESSw.qs"))
Destatw201002
```

```{r estimation with winsorized data, eval = F}
for (Jb in c(2, 10)) {
  if (Jb < 10) Jb <- paste0(0, Jb)
  for (Yr in c(2010, 2012)) {
    LfYr    <- get(paste0("Lfw",    Yr, Jb))
    LfCYr   <- get(paste0("LfwC",   Yr, Jb))
    LfCEYr  <- get(paste0("LfwCE",  Yr, Jb))
    LfCEbYr <- get(paste0("LfwCEb", Yr, Jb))
    LfCEaYr <- get(paste0("LfwCEa", Yr, Jb))
    library(fixest)
    esLfwYr <- feols(JobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfYr)
    esLfwCYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCYr)
    esLfwCEYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCEYr)
    #### Subsample: High and low concentrated markets
    esLfwCEaYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCEaYr)
    esLfwCEbYr <- feols(rJobsMP ~ i(taxyear, FAMP0, ref = 2013)|taxyear + taxrefno + busmainplc_geo, 
      vcov = ~ taxyear + busmainplc_geo,
      data = LfCEbYr)
    library(ggfixest)
    eslistwYr <-  list(
        "All sample" = esLfwYr, 
        "Complete panel" = esLfwCYr, 
        "Existed firms, all sample" = esLfwCEYr, 
        "Existed firms, high concentrated markets" = esLfwCEaYr, 
        "Existed firms, low concentrated markets" = esLfwCEbYr 
      )
    gFEYr <- ggiplot(eslistwYr,
      ref.line = 2012, 
      main = "Job impacts: Low and high concentration, winsorized data",
      xlab = "Tax year (March - Februray)",
      multi_style = "facet",
      geom_style = "ribbon",
      theme = theme(
        axis.text.x = element_text(angle = 90, vjust = .5),
        legend.position = "none"
        )
    ) + 
    scale_x_continuous(limits = c(Yr, 2022), breaks = Yr:2022) +
    scale_y_continuous(limits = c(15, -10)) 
    if (Jb == 2) Jb <- paste0("0", Jb)
    ggsave(
    paste0(pathresults, "Results", Yr, "-2022Job", Jb, "w.jpg")
      , gFE, width = 8*2, height = 4*2, units = "cm",
      dpi = 300
     )
    gFEYr
    lapply(eslistwYr, summary)
    assign(paste0("eslistw", Yr, Jb), eslistwYr)
    assign(paste0("gFEw",    Yr, Jb), gFEYr)
    qsave(eslistwYr, paste0(pathresults, "eslist", Yr, Jb, "w.qs"))
  }
}
gFEw201002
gFEw201202
```

<!-- files to be exported
latex table files for destat 
"Destat201002w_1.tex"
"Destat201002w_2.tex"
  "Destat201002w.tex"
"Destat201202w_1.tex"
"Destat201202w_2.tex"
  "Destat201202w.tex"
"Destat201010w_1.tex"
"Destat201010w_2.tex"
  "Destat201010w.tex"
"Destat201210w_1.tex"
"Destat201210w_2.tex"
  "Destat201210w.tex"

R table files for destat
"DESS.qs"
"DESSw.qs"

estimation result image files
"Results2010-2022Job02.jpg"
"Results2010-2022Job10.jpg"
"Results2012-2022Job02.jpg"
"Results2012-2022Job10.jpg"
"Results2010-2022Job02w.jpg"
"Results2010-2022Job10w.jpg"
"Results2012-2022Job02w.jpg"
"Results2012-2022Job10w.jpg"
-->

