```{r setup, echo = F}
library(qs); library(data.table); library(ggplot2)
library(rmarkdown); library(fixest)
library(knitr); library(tufte)
library(litedown)
library(fasttime)
library(anytime)
#### Set chunk options in litedown
litedown::reactor(
    eval = TRUE
  , echo = TRUE
  , time = TRUE   # record elapsed time of execution
)
options(htmltools.dir.version = FALSE, width = 100)
#### threads
MaxCores <- parallel::detectCores()
DTThreads <- MaxCores - 1
setDTthreads(threads = DTThreads)
setFixest_nthreads(nthreads = DTThreads, save = TRUE)
#### ggplot theme
ThisTheme <- ggplot2::theme(
   axis.text.x = element_text(angle = 90, vjust = .5, hjust = .5), 
   axis.text.y = element_text(size = 12), 
   axis.title = element_text(size = 10), 
   strip.text.x = element_text(color = "blue", size = 8, 
     margin = margin(0, 1.25, 0, 1.25, "cm")), 
   strip.text.y = element_text(color = "blue", size = 8, 
     margin = margin(1.5, 0, 1.5, 0, "cm")),
   panel.spacing.x = unit(c(.1), units = "cm"),
   panel.spacing.y = unit(.1, units = "cm")
)
ThisThemeEnd <- ThisTheme + ggplot2::theme(legend.position="bottom")
#### invalidate cache when the tufte version changes
knitr::opts_chunk$set(
  tidy = FALSE, cache.extra = packageVersion('tufte'), 
  margin_references = TRUE,
  attr.source = ".r .line-numbers",
  #### remove leading hashes in html output
  comment = "", 
  echo = T, cache = F, eval = T,
  class.source = "SeiroBenign", class.output = "SeiroLightGreen"
  )
grepout <- function(str, x)
  # returns element of match (not numbers)
  x[grep(str, x, perl = T)]
table0 <- function(x) table(x, useNA = "ifany")
#### mask_dots: replace every char except positions in `keep` with ".".
#### Used to anonymise taxrefno / uid in display-only prints (not in keys or joins).
mask_dots <- function(x, keep = c(3, 6, 7, 8, 11)) {
  x <- as.character(x)
  n <- nchar(x)
  out <- strrep(".", n)
  for (k in keep) {
    m <- !is.na(x) & n >= k
    substr(out[m], k, k) <- substr(x[m], k, k)
  }
  out
}
read.tablev <- function(fn, quotemark = "", headertrue = TRUE, 
  blskip = TRUE, mat = F, ...) 
{
  x <- read.table(fn, sep = "\t", header = headertrue, blank.lines.skip = blskip, 
        quote = quotemark, na.strings = "", ...)
  if (is.null(dim(x)) | nrow(x) == 1) 
  {
    cn <- names(x)
    dim(x) <- c(1, length(x))
    colnames(x) <- cn
  }
  if (mat) x <- as.matrix(x)
  return(x)
}
write.tablev <- function(x, fn, colnamestrue = TRUE, rownamestrue = FALSE, 
nastrings = "", ...) 
  write.table(x, fn, sep = "\t", quote = FALSE, 
        row.names = rownamestrue, col.names = colnamestrue, na = nastrings, ...)
GeoLevel <- c("Prv", "Dis", "Loc", "Mai")
geovars <- c("busprov_geo", "busdistmuni_geo", 
  "buslocmuni_geo", "busmainplc_geo")
```
```{r path, echo = F}
path <- "W:/epguest/seiro_ito/"
pathprogram <- paste0(path, "outfiles/")
pathdata <- paste0(path, "data/")
pathsaveddata <- paste0(path, "saveddata/")
pathresults <- paste0(path, "results/")
pathdataCITIRP <- "U:/CIT-IRP5 Panel/"
pathdataIRP <- "U:/IRP5/Job level/v5/beta/"
```
